# Generated by Django 4.2 on 2023-08-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0005_event_vat_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, default='', max_length=25)),
                ('seat', models.CharField(blank=True, default='C03', editable=False, max_length=3)),
                ('price', models.FloatField()),
                ('sell_mode', models.CharField(choices=[('W', 'Web'), ('C', 'Cassa'), ('P', 'Prenotazione')], default='C', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.event')),
            ],
        ),
    ]
