# Generated by Django 4.2 on 2023-08-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalmgm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='sell_mode',
            field=models.CharField(default='Cassa', max_length=12),
        ),
    ]
