# Generated by Django 4.2 on 2023-10-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalmgm', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='progres_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
