# Generated by Django 4.2 on 2023-10-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalmgm', '0006_report_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingresso',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='progres_number',
            new_name='progress_number',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
