# Generated by Django 4.2 on 2023-11-03 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_event_vat_rate'),
        ('fiscalmgm', '0007_rename_update_at_ingresso_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFiscalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intero_ticket_serie', models.CharField(default='', max_length=10)),
                ('intero_ticket_start_number', models.IntegerField(max_length=9, verbose_name='Intero dal numero')),
                ('intero_ticket_end_number', models.IntegerField(max_length=9, verbose_name='Intero al numero')),
                ('ridotto_ticket_serie', models.CharField(default='', max_length=10)),
                ('ridotto_ticket_start_number', models.IntegerField(max_length=9, verbose_name='Ridotto dal numero')),
                ('ridotto_ticket_end_number', models.IntegerField(max_length=9, verbose_name='Ridotto al numero')),
                ('gratuito_ticket_serie', models.CharField(default='', max_length=10)),
                ('gratuito_ticket_start_number', models.IntegerField(max_length=9, verbose_name='Gratuito dal numero')),
                ('gratuito_ticket_end_number', models.IntegerField(max_length=9, verbose_name='Gratuito al numero')),
                ('cash_begin_200euro', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Inizio 200 Euro')),
                ('cash_begin_100euro', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Inizio 100 Euro')),
                ('cash_begin_50euro', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Inizio 50 Euro')),
                ('cash_begin_20euro', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Inizio 20 Euro')),
                ('cash_begin_10euro', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Inizio 10 Euro')),
                ('cash_begin_5euro', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Inizio 5 Euro')),
                ('cash_begin_2euro', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Inizio 2 Euro')),
                ('cash_begin_1euro', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Inizio 1 Euro')),
                ('cash_begin_50cent', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Inizio 50 Cent')),
                ('cash_begin_20cent', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Inizio 20 Cent')),
                ('cash_begin_10cent', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Inizio 10 Cent')),
                ('cash_end_200euro', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Fine 200 Euro')),
                ('cash_end_100euro', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Fine 100 Euro')),
                ('cash_end_50euro', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Fine 50 Euro')),
                ('cash_end_20euro', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Fine 20 Euro')),
                ('cash_end_10euro', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Fine 10 Euro')),
                ('cash_end_5euro', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Fine 5 Euro')),
                ('cash_end_2euro', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Fine 2 Euro')),
                ('cash_end_1euro', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Fine 1 Euro')),
                ('cash_end_50cent', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Fine 50 Cent')),
                ('cash_end_20cent', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Fine 20 Cent')),
                ('cash_end_10cent', models.SmallIntegerField(default=0, max_length=3, null=True, verbose_name='Num. Fine 10 Cent')),
                ('collection_satispay', models.FloatField(default=0.0, null=True, verbose_name='Incasso Satispay Euro')),
                ('collection_sumup', models.FloatField(default=0.0, null=True, verbose_name='Incasso Sumup Euro')),
                ('collection_others', models.FloatField(default=0.0, null=True, verbose_name='Incasso Altri Euro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.event')),
            ],
        ),
    ]
