# Generated by Django 4.2 on 2023-11-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalmgm', '0008_eventfiscaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_begin_100euro',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Inizio 100 Euro'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_begin_10cent',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Inizio 10 Cent'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_begin_10euro',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Inizio 10 Euro'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_begin_1euro',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Inizio 1 Euro'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_begin_200euro',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Inizio 200 Euro'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_begin_20cent',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Inizio 20 Cent'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_begin_20euro',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Inizio 20 Euro'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_begin_2euro',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Inizio 2 Euro'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_begin_50cent',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Inizio 50 Cent'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_begin_50euro',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Inizio 50 Euro'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_begin_5euro',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Inizio 5 Euro'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_end_100euro',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Fine 100 Euro'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_end_10cent',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Fine 10 Cent'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_end_10euro',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Fine 10 Euro'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_end_1euro',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Fine 1 Euro'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_end_200euro',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Fine 200 Euro'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_end_20cent',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Fine 20 Cent'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_end_20euro',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Fine 20 Euro'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_end_2euro',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Fine 2 Euro'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_end_50cent',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Fine 50 Cent'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_end_50euro',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Fine 50 Euro'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='cash_end_5euro',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Num. Fine 5 Euro'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='gratuito_ticket_end_number',
            field=models.IntegerField(verbose_name='Gratuito al numero'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='gratuito_ticket_start_number',
            field=models.IntegerField(verbose_name='Gratuito dal numero'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='intero_ticket_end_number',
            field=models.IntegerField(verbose_name='Intero al numero'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='intero_ticket_start_number',
            field=models.IntegerField(verbose_name='Intero dal numero'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='ridotto_ticket_end_number',
            field=models.IntegerField(verbose_name='Ridotto al numero'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='ridotto_ticket_start_number',
            field=models.IntegerField(verbose_name='Ridotto dal numero'),
        ),
    ]
