# Generated by Django 4.2 on 2023-11-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalmgm', '0009_alter_eventfiscaldata_cash_begin_100euro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfiscaldata',
            name='casher_01',
            field=models.CharField(default='Nome Cognome', max_length=50, verbose_name='Nome e cognome persona in cassa 1'),
        ),
        migrations.AddField(
            model_name='eventfiscaldata',
            name='casher_02',
            field=models.CharField(default='Nome Cognome', max_length=50, verbose_name='Nome e cognome persona in cassa 2'),
        ),
    ]
