# Generated by Django 4.2 on 2023-11-06 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_event_vat_rate'),
        ('fiscalmgm', '0010_eventfiscaldata_casher_01_eventfiscaldata_casher_02'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='casher_01',
            field=models.CharField(default='Nome Cognome1', max_length=50, verbose_name='Nome e cognome persona in cassa 1'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='casher_02',
            field=models.CharField(default='Nome Cognome2', max_length=50, verbose_name='Nome e cognome persona in cassa 2'),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.event', unique=True),
        ),
    ]
