# Generated by Django 4.2 on 2023-11-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_event_vat_rate'),
        ('fiscalmgm', '0011_alter_eventfiscaldata_casher_01_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.event'),
        ),
    ]
