# Generated by Django 4.2 on 2023-11-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalmgm', '0013_alter_eventfiscaldata_gratuito_ticket_end_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfiscaldata',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
