# Generated by Django 4.2 on 2023-11-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalmgm', '0015_rename_gratuito_ticket_end_number_eventfiscaldata_gratuito_ticket_end_number_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='gratuito_ticket_serie_2',
            field=models.CharField(default='nd', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='intero_ticket_serie_2',
            field=models.CharField(default='nd', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventfiscaldata',
            name='ridotto_ticket_serie_2',
            field=models.CharField(default='nd', max_length=10),
        ),
    ]
