# Generated by Django 4.2 on 2023-11-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalmgm', '0016_alter_eventfiscaldata_gratuito_ticket_serie_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfiscaldata',
            name='collection_presell',
            field=models.FloatField(default=0.0, null=True, verbose_name='Prevendita Euro'),
        ),
    ]
