# Generated by Django 4.2 on 2024-01-30 10:15

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalmgm', '0017_eventfiscaldata_collection_presell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='doc_path',
            field=models.FilePathField(default='dummy.xls', editable=False, path=pathlib.PurePosixPath('/home/beppe/project/clone_ltcboxoffice/ltcboxoffice/media/siae_reports'), verbose_name='report file path'),
        ),
    ]
