# Generated by Django 4.2.11 on 2025-11-16 23:48

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalmgm', '0019_alter_report_doc_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='doc_path',
            field=models.FilePathField(default='dummy.xls', editable=False, path=pathlib.PureWindowsPath('C:/Users/Asus/projects/python/ltcboxoffice/media/siae_reports'), verbose_name='report file path'),
        ),
    ]
