# Generated by Django 4.2.11 on 2025-11-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalmgm', '0020_alter_report_doc_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfiscaldata',
            name='abbonamento_ticket_end_number_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Abbonamento al numero'),
        ),
        migrations.AddField(
            model_name='eventfiscaldata',
            name='abbonamento_ticket_end_number_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Abbonamento al numero'),
        ),
        migrations.AddField(
            model_name='eventfiscaldata',
            name='abbonamento_ticket_serie_1',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='eventfiscaldata',
            name='abbonamento_ticket_serie_2',
            field=models.CharField(blank=True, default='nd', max_length=10),
        ),
        migrations.AddField(
            model_name='eventfiscaldata',
            name='abbonamento_ticket_start_number_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Abbonamento dal numero'),
        ),
        migrations.AddField(
            model_name='eventfiscaldata',
            name='abbonamento_ticket_start_number_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Abbonamento dal numero'),
        ),
    ]
