# Generated by Django 4.2.11 on 2025-11-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalmgm', '0021_add_abbonamento_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfiscaldata',
            name='abbonamento_ticket_end_number_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Abbonamento al numero'),
        ),
        migrations.AddField(
            model_name='eventfiscaldata',
            name='abbonamento_ticket_end_number_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Abbonamento al numero'),
        ),
        migrations.AddField(
            model_name='eventfiscaldata',
            name='abbonamento_ticket_serie_3',
            field=models.CharField(blank=True, default='nd', max_length=10),
        ),
        migrations.AddField(
            model_name='eventfiscaldata',
            name='abbonamento_ticket_serie_4',
            field=models.CharField(blank=True, default='nd', max_length=10),
        ),
        migrations.AddField(
            model_name='eventfiscaldata',
            name='abbonamento_ticket_start_number_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Abbonamento dal numero'),
        ),
        migrations.AddField(
            model_name='eventfiscaldata',
            name='abbonamento_ticket_start_number_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Abbonamento dal numero'),
        ),
    ]
