# Generated by Django 4.2 on 2023-04-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_event_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
