# Generated by Django 4.2 on 2023-05-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_event_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vat_rate',
            field=models.FloatField(default=10),
        ),
    ]
