# Generated by Django 4.2 on 2024-04-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0015_venue_local_code_siae'),
        ('store', '0005_event_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='billboard.venue'),
        ),
    ]
