# Generated by Django 4.2.11 on 2025-11-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking_deadline_hours',
            field=models.PositiveIntegerField(default=3, help_text="Numero di ore prima dell'evento entro cui è possibile prenotare (da 1 a 24 ore)", verbose_name='Ore limite prenotazione'),
        ),
    ]
