# Generated by Django 4.2 on 2023-05-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cartitem_ingresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='seat',
            field=models.CharField(default='C03', max_length=3),
        ),
    ]
