# Generated by Django 4.2 on 2023-08-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='ingresso',
            field=models.IntegerField(choices=[(0, 'Gratuito'), (1, 'Intero'), (2, 'Ridotto')], default=2),
        ),
    ]
