# Generated by Django 4.2 on 2023-08-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_alter_cartitem_ingresso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='ingresso',
            field=models.IntegerField(choices=[(0, 'Gratuito'), (1, 'Ridotto'), (2, 'Intero')], default=2),
        ),
    ]
