# Generated by Django 4.2.11 on 2025-11-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_alter_cartitem_ingresso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='ingresso',
            field=models.IntegerField(choices=[(0, 'Gratuito'), (1, 'Ridotto'), (2, 'Intero'), (3, 'Abbonamento R4'), (4, 'Abbonamento R8'), (5, 'Abbonamento I4'), (6, 'Abbonamento I8')], default=2),
        ),
    ]
