# Generated by Django 4.2 on 2023-06-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='postal_code',
            new_name='post_code',
        ),
    ]
