# Generated by Django 4.2.11 on 2026-07-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_postal_code_userprofile_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='migrated_from_old_site',
            field=models.BooleanField(default=False),
        ),
    ]
