# Generated by Django 4.2.11 on 2026-07-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_migrated_from_old_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_socio',
            field=models.BooleanField(default=False),
        ),
    ]
