# Generated by Django 4.2 on 2025-07-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billboard', '0015_venue_local_code_siae'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shw_title', models.CharField(default='My Title', max_length=100)),
                ('shw_theater_company', models.CharField(default='Laboratorio Teatrale di Cambiano', max_length=100)),
                ('shw_author', models.CharField(default='My Author', max_length=100)),
                ('shw_director', models.CharField(default='My Director', max_length=100)),
                ('shw_slug', models.SlugField(max_length=200, unique=True)),
                ('shw_date', models.DateField()),
                ('shw_description', models.TextField(blank=True, max_length=2048)),
                ('shw_image', models.ImageField(blank=True, default='photos/history/poster_globe_theatre.jpg', upload_to='photos/history')),
                ('shw_section', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='billboard.section')),
                ('shw_siaetype', models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='billboard.siaetype')),
                ('shw_venue', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='billboard.venue')),
            ],
        ),
    ]
