# Generated by Django 4.2 on 2025-07-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0015_venue_local_code_siae'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyshow',
            name='shw_siaetype',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='billboard.siaetype'),
        ),
    ]
