# Generated by Django 4.2 on 2025-07-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_historyshow_shw_siaetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyshow',
            name='shw_description',
        ),
        migrations.AddField(
            model_name='historyshow',
            name='shw_spectators',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
