# Generated by Django 4.2 on 2025-07-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_remove_historyshow_shw_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyshow',
            name='shw_description',
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
