# Generated by Django 4.2 on 2025-07-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_historyshow_shw_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_label', models.CharField(blank=True, max_length=50, unique=True)),
                ('season_start_date', models.DateField()),
                ('season_end_date', models.DateField()),
                ('season_description', models.TextField(blank=True, max_length=2048)),
            ],
        ),
    ]
