# Generated by Django 4.2 on 2025-07-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyshow',
            name='shw_season',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='history.season'),
        ),
    ]
