# Generated by Django 4.2 on 2023-04-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=512)),
                ('shw_code', models.CharField(blank=True, max_length=8, unique=True)),
                ('shw_image', models.ImageField(blank=True, upload_to='photos/billboard')),
                ('is_in_billboard', models.BooleanField(blank=True, default=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
