# Generated by Django 4.2 on 2023-04-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='shw_title',
            field=models.CharField(default='My Title', max_length=100),
        ),
    ]
