# Generated by Django 4.2 on 2023-04-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0003_alter_show_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='responsible_mail',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
