# Generated by Django 4.2 on 2023-04-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0004_show_responsible_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='responsible_mail',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
    ]
