# Generated by Django 4.2 on 2023-04-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0006_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='default_price_full',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='default_price_reduced',
            field=models.CharField(max_length=50),
        ),
    ]
