# Generated by Django 4.2 on 2023-04-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0007_alter_section_default_price_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='section',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='billboard.section'),
        ),
    ]
