# Generated by Django 4.2 on 2023-10-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0008_show_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='shw_author',
            field=models.CharField(default='My Author', max_length=100),
        ),
        migrations.AddField(
            model_name='show',
            name='shw_theater_company',
            field=models.CharField(default='Laboratorio Teatrale di Cambiano', max_length=100),
        ),
    ]
