# Generated by Django 4.2 on 2023-10-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0009_show_shw_author_show_shw_theater_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='shw_director',
            field=models.CharField(default='My Director', max_length=100),
        ),
    ]
