# Generated by Django 4.2 on 2023-10-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0010_show_shw_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiaeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('description', models.CharField(max_length=120)),
                ('iva', models.PositiveSmallIntegerField(default=10)),
            ],
        ),
    ]
