# Generated by Django 4.2 on 2023-10-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0011_siaetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='siaetype',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='billboard.siaetype'),
        ),
    ]
