# Generated by Django 4.2 on 2024-04-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0012_show_siaetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=234)),
            ],
        ),
    ]
