# Generated by Django 4.2 on 2024-04-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0013_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='ba_code_siae',
            field=models.CharField(default='0050450366484', max_length=13),
        ),
    ]
