# Generated by Django 4.2 on 2024-04-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0014_venue_ba_code_siae'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='local_code_siae',
            field=models.CharField(default='  045', max_length=5),
        ),
    ]
