# Generated by Django 4.2.11 on 2025-11-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0015_venue_local_code_siae'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='configuration_file',
            field=models.FileField(blank=True, help_text='Upload venue seating configuration file (JSON or XML format)', null=True, upload_to='venue_configs/'),
        ),
    ]
