# Generated by Django 4.2.11 on 2025-11-15 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0016_remove_userevent_seats_price'),
        ('store', '0007_alter_event_venue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Es: Abbonamento 4 ingressi ridotti', max_length=100, verbose_name='Nome Abbonamento')),
                ('code_prefix', models.CharField(help_text='Es: R4, I8, I4, R8', max_length=10, verbose_name='Prefisso Codice')),
                ('type', models.CharField(choices=[('FULL', 'Intero'), ('REDUCED', 'Ridotto'), ('COMPLIMENTARY', 'Omaggio')], default='FULL', max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Percentuale sconto rispetto al prezzo pieno', max_digits=5, verbose_name='Sconto %')),
                ('max_events', models.PositiveIntegerField(verbose_name='Numero Eventi Inclusi')),
                ('valid_days', models.PositiveIntegerField(default=365, verbose_name='Giorni di Validità')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo Abbonamento',
                'verbose_name_plural': 'Tipi Abbonamento',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_number', models.CharField(max_length=50, unique=True, verbose_name='Numero Abbonamento')),
                ('valid_from', models.DateField(verbose_name='Valido Da')),
                ('valid_to', models.DateField(verbose_name='Valido Fino')),
                ('events_included', models.PositiveIntegerField(verbose_name='Eventi Inclusi')),
                ('events_used', models.PositiveIntegerField(default=0, verbose_name='Eventi Utilizzati')),
                ('barcode_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='Percorso Barcode')),
                ('status', models.CharField(choices=[('ACTIVE', 'Attivo'), ('EXPIRED', 'Scaduto'), ('EXHAUSTED', 'Esaurito'), ('CANCELLED', 'Annullato')], default='ACTIVE', max_length=20, verbose_name='Stato')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment', verbose_name='Pagamento')),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptiontype', verbose_name='Tipo Abbonamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Abbonamento',
                'verbose_name_plural': 'Abbonamenti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=10, verbose_name='Posto')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Ora Utilizzo')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.event', verbose_name='Evento')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment', verbose_name='Pagamento Associato')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='subscriptions.subscription', verbose_name='Abbonamento')),
                ('used_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_validations', to=settings.AUTH_USER_MODEL, verbose_name='Validato Da')),
            ],
            options={
                'verbose_name': 'Utilizzo Abbonamento',
                'verbose_name_plural': 'Utilizzi Abbonamenti',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['subscription', 'event'], name='subscriptio_subscri_4f1114_idx'), models.Index(fields=['event', 'used_at'], name='subscriptio_event_i_483de5_idx')],
                'unique_together': {('subscription', 'event', 'seat')},
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscription_number'], name='subscriptio_subscri_c33376_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_2a19e8_idx'),
        ),
    ]
