# Generated by Django 4.2 on 2023-06-29 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0005_event_vat_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=3, verbose_name='Posto')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.event')),
            ],
        ),
    ]
