# Generated by Django 4.2 on 2024-02-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellingSeats',
        ),
    ]
