# Generated by Django 4.2 on 2023-06-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingseats',
            name='price',
            field=models.IntegerField(choices=[(0, 'Gratuito'), (1, 'Intero'), (2, 'Ridotto')], default=1),
        ),
    ]
