# Generated by Django 4.2 on 2023-06-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0002_sellingseats_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingseats',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
