# Generated by Django 4.2 on 2024-02-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0005_event_vat_rate'),
        ('boxoffice', '0002_delete_sellingseats'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=3, verbose_name='Posto')),
                ('price', models.IntegerField(choices=[(0, 'Gratuito'), (1, 'Ridotto'), (2, 'Intero')], default=0)),
                ('cost', models.FloatField(default=0.0)),
                ('ingresso', models.CharField(default='Gratuito', max_length=12)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.event')),
            ],
        ),
    ]
