# Generated by Django 4.2 on 2023-06-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0003_sellingseats_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingseats',
            name='ingresso',
            field=models.CharField(default='Gratuito', max_length=12),
        ),
    ]
