# Generated by Django 4.2 on 2024-02-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=25, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.IntegerField(choices=[(0, 'Cassa'), (1, 'Bank'), (2, 'Satispay'), (3, 'Sumup')], default=0)),
                ('commission_model', models.IntegerField(choices=[(0, 'No commission'), (1, 'Perc 2%'), (2, 'Fixed on threshold 10 Euro')], default=0)),
            ],
        ),
    ]
