# Generated by Django 4.2 on 2023-06-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0004_sellingseats_ingresso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingseats',
            name='price',
            field=models.IntegerField(choices=[(0, 'Gratuito'), (1, 'Ridotto'), (2, 'Intero')], default=0),
        ),
    ]
