# Generated by Django 4.2 on 2024-02-14 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderevent_expired'),
        ('boxoffice', '0006_sellingseats_orderevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingseats',
            name='orderevent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderevent'),
        ),
    ]
