# Generated by Django 4.2 on 2024-05-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0007_alter_sellingseats_orderevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=20)),
                ('post_code', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
    ]
