# Generated by Django 4.2 on 2024-06-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0009_boxofficebookingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingseats',
            name='orderevent',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
