# Generated by Django 4.2.11 on 2025-11-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0010_alter_sellingseats_orderevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingseats',
            name='ingresso',
            field=models.CharField(default='Gratuito', max_length=20),
        ),
        migrations.AlterField(
            model_name='sellingseats',
            name='price',
            field=models.IntegerField(choices=[(0, 'Gratuito'), (1, 'Ridotto'), (2, 'Intero'), (3, 'Abbonamento R4'), (4, 'Abbonamento R8'), (5, 'Abbonamento I4'), (6, 'Abbonamento I8')], default=0),
        ),
    ]
