# Generated by Django 4.2.11 on 2025-11-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0011_alter_sellingseats_ingresso_alter_sellingseats_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingseats',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
