# Generated by Django 4.2.11 on 2025-11-18 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0012_sellingseats_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingseats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
