# Generated by Django 4.2.11 on 2025-11-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0013_sellingseats_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingseats',
            name='subscription_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codice Abbonamento'),
        ),
    ]
