# Generated by Django 4.2 on 2023-04-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='num_in_row',
            field=models.CharField(max_length=2),
        ),
    ]
