# Generated by Django 4.2 on 2023-04-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_alter_seat_num_in_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True)),
                ('offset_start', models.IntegerField()),
                ('offset_end', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
