# Generated by Django 4.2 on 2023-05-25 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_rename_seat_orderevent_seats_price_and_more'),
        ('hall', '0003_row'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_event_vat_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('event', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='store.event')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.payment')),
                ('seat', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hall.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
