# Generated by Django 4.2 on 2023-05-26 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_seat_orderevent_seats_price_and_more'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.AddField(
            model_name='ticket',
            name='orderevent',
            field=models.ForeignKey(blank=True, default=20, editable=False, on_delete=django.db.models.deletion.CASCADE, to='orders.orderevent'),
        ),
    ]
