# Generated by Django 4.2 on 2023-06-16 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_userevent'),
        ('tickets', '0003_ticket_created_at_ticket_number_ticket_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sell_mode',
            field=models.CharField(choices=[('W', 'Web'), ('C', 'Cassa'), ('P', 'Prenotazione')], default='W', max_length=12),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.payment'),
        ),
    ]
