# Generated by Django 4.2 on 2023-06-19 08:28

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pdf_path',
            field=models.FilePathField(default='dummy.pdf', path=pathlib.PurePosixPath('/home/beppe/project/ltcboxoffice/media/tickets'), verbose_name='pdf file path'),
        ),
    ]
