# Generated by Django 4.2 on 2023-07-05 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_userevent'),
        ('tickets', '0007_alter_ticket_pdf_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.payment'),
        ),
    ]
