# Generated by Django 4.2 on 2023-07-05 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_userevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0008_alter_ticket_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='orderevent',
            field=models.ForeignKey(blank=True, default=20, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderevent'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
