# Generated by Django 4.2 on 2024-01-30 10:15

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pdf_path',
            field=models.FilePathField(default='dummy.pdf', editable=False, path=pathlib.PurePosixPath('/home/beppe/project/clone_ltcboxoffice/ltcboxoffice/media/tickets'), verbose_name='pdf file path'),
        ),
    ]
