# Generated by Django 4.2 on 2024-06-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_ticket_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='orderevent',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
