# Generated by Django 4.2 on 2024-07-05 21:16

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_ticket_orderevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pdf_path',
            field=models.FilePathField(default='dummy.pdf', editable=False, path=pathlib.PurePosixPath('/home/ltc/projects/ltcboxoffice/media/tickets'), verbose_name='pdf file path'),
        ),
    ]
