# Generated by Django 4.2.11 on 2025-11-16 23:48

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_ticket_pdf_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pdf_path',
            field=models.FilePathField(default='dummy.pdf', editable=False, path=pathlib.PureWindowsPath('C:/Users/Asus/projects/python/ltcboxoffice/media/tickets'), verbose_name='pdf file path'),
        ),
    ]
