# Generated by Django 4.2.11 on 2025-11-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_alter_ticket_pdf_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=25),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event', 'seat'], name='ticket_event_seat_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('number__gt', '')), fields=('number',), name='unique_ticket_number'),
        ),
    ]
