# Generated by Django 4.2 on 2023-05-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_country_order_post_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderevent',
            old_name='event_price',
            new_name='order_price',
        ),
        migrations.RemoveField(
            model_name='orderevent',
            name='event_seat',
        ),
        migrations.RemoveField(
            model_name='orderevent',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderevent',
            name='items',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
