# Generated by Django 4.2 on 2023-05-22 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_event_vat_rate'),
        ('orders', '0003_rename_event_price_orderevent_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderevent',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.event'),
        ),
    ]
