# Generated by Django 4.2 on 2023-05-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderevent_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderevent',
            old_name='items',
            new_name='seat',
        ),
        migrations.AddField(
            model_name='orderevent',
            name='ingresso',
            field=models.IntegerField(default=0),
        ),
    ]
