# Generated by Django 4.2 on 2024-02-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderevent_barcode_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderevent',
            name='orderevent_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
