# Generated by Django 4.2 on 2024-02-01 14:45

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderevent_orderevent_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='barcode_path',
            field=models.FilePathField(blank=True, max_length=512, null=True, path=orders.models.barcode_image_path),
        ),
    ]
