# Generated by Django 4.2 on 2024-02-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderevent_barcode_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderevent',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
