# Generated by Django 4.2 on 2024-02-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderevent_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
