# Generated by Django 4.2.11 on 2026-06-23 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0016_remove_userevent_seats_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.IntegerField(choices=[(1, 'Creata'), (2, 'Evasa'), (3, 'Cancellata'), (4, 'Modificata'), (5, 'Altro')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orderevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.orderevent')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
